# Generated by Django 5.1.1 on 2024-10-03 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('five', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModel',
            new_name='MyModel',
        ),
    ]
